batch: 512
n0: 200
maxn: 1000
alpha: 0.001
adaptive: False
log_dir: "./results/script_results/"
NUM_IMAGES_FOR_TEST: 500


device: "cuda"
gpu: 1

dataset: "imagenet"
arch: "resnet50"
num_classes: 1000
base_classifier: "./checkpoints/trans_blur_bright_contrast/TransBrightBlurContrast_40_04_10_04_checkpoint.pth.tar"


transform: "ct"
dimenshion: 3
b_zero: [1.0, 0, 0]
x0: [1.1, 0.3, -10.0]


sigmas:
    sigma_b:
    sigma_c: 0.4
    sigma_tr: 30
    sigma_gamma:
    sigma_blur:

ns: 20000
betas_estimation:
    beta0:
        left: 0.5
        right: 1.5
        db: 13
    beta1:
        left: -60
        right: 60
        db: 17
    beta2:
        left: -60
        right: 60
        db: 17
        
betas_certification:
    beta0:
        left: 0.8
        right: 1.2
        db: 11
    beta1:
        left: -25
        right: 25
        db: 11
    beta2:
        left: -25
        right: 25
        db: 11
        
calculate_f_era: False
calculate_h_era: False

hlist:
    left: 0.5
    right: 1.0
    n_steps: 1001 