batch: 512
n0: 200
maxn: 1000
alpha: 0.001
adaptive: False
log_dir: "./results/script_results/"
NUM_IMAGES_FOR_TEST: 500


device: "cuda"
gpu: 1

dataset: "imagenet"
arch: "resnet50"
num_classes: 1000
base_classifier: "./checkpoints/brightness/checkpoint.pth.tar"


transform: "cbt"
dimenshion: 4
b_zero: [1.0, 0, 0, 0]
x0: [0.2 ,1.0, 3., 1]


sigmas:
    sigma_b: 0.4
    sigma_c: 0.4
    sigma_tr: 10
    sigma_gamma:
    sigma_blur:

ns: 20000
betas_estimation:
    beta0:
        left: 0.7
        right: 1.3
        db: 7
    beta1:
        left: -0.3
        right: 0.3
        db: 7
    beta2:
        left: -45
        right: 45
        db: 5
    beta3:
        left: -30
        right: 30
        db: 5
        
betas_certification:
    beta0:
        left: 0.8
        right: 1.2
        db: 17
    beta1:
        left: -0.2
        right: 0.2
        db: 13
    beta2:
        left: -15
        right: 15
        db: 11
    beta3:
        left: -15
        right: 15
        db: 11
        
calculate_f_era: False
calculate_h_era: False

hlist:
    left: 0.5
    right: 1.0
    n_steps: 1001 