wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.12
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1683908026.259787
    t:
      1:
      - 1
      - 12
      - 41
      - 55
      - 79
      2:
      - 1
      - 12
      - 41
      - 55
      - 79
      3:
      - 2
      - 13
      - 15
      - 23
      4: 3.8.12
      5: 0.15.2
      8:
      - 1
      - 5
