batch: 512
n0: 200
maxn: 1000
alpha: 0.001
adaptive: False
log_dir: "./results/script_results/"
NUM_IMAGES_FOR_TEST: 500


device: "cuda"
gpu: 1

dataset: "cifar10"
arch: "cifar_resnet110"
num_classes: 10
base_classifier: "./tss_weights/cifar10/resnet110/translation/noise_15.0/consistency/checkpoint.pth.tar"


transform: "tr"
dimenshion: 2
b_zero: [0, 0]
x0: [1.1, 12]


sigmas:
    sigma_b: 
    sigma_c: 
    sigma_tr: 15
    sigma_gamma:
    sigma_blur:

ns: 20000
betas_estimation:
    beta0:
        left: -25
        right: 25
        db: 21
    beta1:
        left: -25
        right: 25
        db: 21
        
betas_certification:
    beta0:
        left: -14.18
        right: 14.18
        db: 11
    beta1:
        left: -14.18
        right: 14.18
        db: 11
        
calculate_f_era: False
calculate_h_era: False

hlist:
    left: 0.5
    right: 1.0
    n_steps: 1001 