batch: 512
n0: 200
maxn: 1000
alpha: 0.001
adaptive: False
log_dir: "./results/script_results/"
NUM_IMAGES_FOR_TEST: 500


device: "cuda"
gpu: 1

dataset: "imagenet"
arch: "resnet50"
num_classes: 1000
base_classifier: "./checkpoints/trans_blur_bright_contrast/TransBrightBlurContrast_40_04_10_04_checkpoint.pth.tar"


transform: "tr"
dimenshion: 2
b_zero: [0, 0]
x0: [1.1, 12]


sigmas:
    sigma_b: 
    sigma_c: 
    sigma_tr: 50
    sigma_gamma:
    sigma_blur:

ns: 20000
betas_estimation:
    beta0:
        left: -150
        right: 150
        db: 41
    beta1:
        left: -150
        right: 150
        db: 41
        
betas_certification:
    beta0:
        left: -56
        right: 56
        db: 11
    beta1:
        left: -56
        right: 56
        db: 11
        
calculate_f_era: False
calculate_h_era: False

hlist:
    left: 0.5
    right: 1.0
    n_steps: 1001 