batch: 512
n0: 200
maxn: 1000
alpha: 0.001
adaptive: False
log_dir: "./results/script_results/"
NUM_IMAGES_FOR_TEST: 500


device: "cuda"
gpu: 1

dataset: "imagenet"
arch: "resnet50"
num_classes: 1000
base_classifier: "./checkpoints/_GCGCGC_checkpoint.pth.tar"


transform: "gc"
dimenshion: 2
b_zero: [1, 1]
x0: [1.1, 1.3]


sigmas:
    sigma_b: 
    sigma_c: 0.1
    sigma_tr:
    sigma_gamma: 0.1
    sigma_blur:

ns: 20000
betas_estimation:
    beta0:
        left: 0.4
        right: 2.2
        db: 51
    beta1:
        left: 0.4
        right: 2.2
        db: 53
        
betas_certification:
    beta0:
        left: 0.8
        right: 1.4
        db: 35
    beta1:
        left: 0.6
        right: 2.0
        db: 31
        
calculate_f_era: False
calculate_h_era: False

hlist:
    left: 0.5
    right: 1.0
    n_steps: 1001 