batch: 512
n0: 200
maxn: 1000
alpha: 0.001
adaptive: False
log_dir: "./results/script_results/"
NUM_IMAGES_FOR_TEST: 500


device: "cuda"
gpu: 1

dataset: "cifar100"
arch: "cifar100_resnet110"
num_classes: 100
base_classifier: "./new_results/cifar100_resnet110_cifar100_cb_cifar100_cb_checkpoint.pth.tar"


transform: "cb"
dimenshion: 2
b_zero: [1, 0]
x0: [1.1, 1.3]


sigmas:
    sigma_b: 0.3
    sigma_c: 0.3
    sigma_tr:
    sigma_gamma:
    sigma_blur:

ns: 20000
betas_estimation:
    beta0:
        left: 0.5
        right: 1.5
        db: 40
    beta1:
        left: -0.5
        right: 0.5
        db: 42
        
betas_certification:
    beta0:
        left: 0.6
        right: 1.4
        db: 35
    beta1:
        left: -0.4
        right: 0.4
        db: 31
        
calculate_f_era: False
calculate_h_era: False

hlist:
    left: 0.5
    right: 1.0
    n_steps: 1001 