batch: 512
n0: 200
maxn: 1000
alpha: 0.001
adaptive: False
log_dir: "./logs/script_results/"
NUM_IMAGES_FOR_TEST: 500


device: "cuda"
gpu: 1

dataset: "cifar10"
arch: "cifar_resnet110"
num_classes: 10
base_classifier: "./tss_weights/cifar10/resnet110/brightness-contrast/0.3_0.3/consistency/checkpoint.pth.tar"


transform: "cb"
dimenshion: 2
b_zero: [1, 0]
x0: [1.1, 1.3]


sigmas:
    sigma_b: 0.3
    sigma_c: 0.3
    sigma_tr:
    sigma_blur:
    sigma_gamma:

ns: 20000
betas_estimation:
    beta0:
        left: 0.5
        right: 1.5
        db: 41
    beta1:
        left: -0.5
        right: 0.5
        db: 43
        
betas_certification:
    beta0:
        left: 1.4
        right: 1.4
        db: 35
    beta1:
        left: -0.4
        right: 0.4
        db: 41
        
calculate_f_era: True
calculate_h_era: True

hlist:
    left: 0.5
    right: 1.0
    n_steps: 1001 