transform: "cb"
dimenshion: 2
dataset: "imagenet"
base_classifier: "../../checkpoints/brightness/checkpoint.pth.tar"
device: "cuda"
arch: "resnet50"
gpu: 5
sigmas:
    sigma_b: 0.3
    sigma_c: 0.3
    sigma_tr:
    sigma_blur:
    sigma_gamma:
betas_estimation:
    beta0:
        left: 0.5
        right: 1.5
        db: 21
    beta1:
        left: -0.5
        right: 0.5
        db: 23
        
betas_certification:
    beta0:
        left: 1.4
        right: 1.4
        db: 35
    beta1:
        left: -0.4
        right: 0.4
        db: 41