batch: 512
n0: 200
maxn: 1000
alpha: 0.001
adaptive: False
log_dir: "./results/script_results/"
NUM_IMAGES_FOR_TEST: 500


device: "cuda"
gpu: 1

dataset: "cifar100"
arch: "cifar100_resnet110"
num_classes: 100
base_classifier: "./new_results/cifar100_resnet110_cifar100_cb_cifar100_cb_checkpoint.pth.tar"


transform: "c"
dimenshion: 1
b_zero: [1.0]
x0: [1.2]


sigmas:
    sigma_b:
    sigma_c: 0.3
    sigma_tr:
    sigma_gamma:
    sigma_blur:

ns: 50000
betas_estimation:
    beta0:
        left: 1.0
        right: 1.5
        db: 201
        
betas_certification:
    beta0:
        left: 1.0
        right: 1.4
        db: 41

        
calculate_f_era: False
calculate_h_era: False

hlist:
    left: 0.5
    right: 1.0
    n_steps: 1001 