batch: 512
n0: 200
maxn: 1000
alpha: 0.001
adaptive: False
log_dir: "./results/script_results/"
NUM_IMAGES_FOR_TEST: 500


device: "cuda"
gpu: 1

dataset: "imagenet"
arch: "resnet50"
num_classes: 1000
base_classifier: "./tss_weights/imagenet/resnet50/brightness-contrast/0.4_0.4/consistency/checkpoint.pth.tar"


transform: "b"
dimenshion: 1
b_zero: [0.0]
x0: [0.3]


sigmas:
    sigma_b: 0.3
    sigma_c: 
    sigma_tr:
    sigma_gamma:
    sigma_blur:

ns: 20000
betas_estimation:
    beta0:
        left: -0.5
        right: 0.5
        db: 51
        
betas_certification:
    beta0:
        left: -0.4
        right: 0.4
        db: 35

        
calculate_f_era: False
calculate_h_era: False

hlist:
    left: 0.5
    right: 1.0
    n_steps: 1001 