corrupt: "contrast"
noise_sd: 0.3
noise_dst: "gaussian"
partial_max: 0.3
dataset: "imagenet"
base_classifier: "../../tss_weights/imagenet/resnet50/brightness-contrast/0.4_0.4/consistency/checkpoint.pth.tar"
device: "cuda"
arch: "resnet50"
gpu: 5